# Configuration file for ML project

paths:
  train_file: 'data/train_ver2.csv'
  test_file: 'data/test_ver2.csv'

als_params:
  random_state: 42
  factors: 100
  regularization: 0.1
  iterations: 50

metrics:
  top_k: 7  # Top K recommendations value

cols:
  client_id: "ncodpers"
  item_id: " "
